services:
  - type: web
    name: expense-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        scope: run
      - key: PYTHON_VERSION
        value: 3.12.7
        scope: run
      - key: WEBAPP_URL
        scope: run
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        scope: run
